run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - bodyclose
    - noctx
    - gosec
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - goconst
    - gocritic
    - misspell
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  govet:
    shadow: true
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: unexported-return
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - goconst
        - unparam
    - path: docs/
      linters:
        - all
