FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /notifications ./cmd/notifications

FROM alpine:3.21

WORKDIR /app

COPY --from=builder /notifications /notifications

CMD ["/notifications"]
