FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /products ./cmd/products

FROM alpine:3.21

WORKDIR /app

COPY --from=builder /products /products
COPY migrations /app/migrations

EXPOSE 8080

CMD ["/products"]
